release:
  github:
    owner: neicnordic
    name: crypt4gh

builds:
  - goos:
      - darwin
      - linux
      - windows
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- tolower .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
